### ISSUE TITLE
Request for Pre-trained Model Files

### ISSUE THREAD

**Issue by xiaohuahuaw** [Shanka123/STSN#1]
Thank you for your outstanding work! Due to limitations in my device's computing capacity, I am inquiring if it's possible to obtain pre-trained model files. I will adhere to all relevant regulations and appreciate your assistance.

Thank you!

**Comment by Shanka123** [comment]
Thank you for your interest in this work. The pre-trained model files for the three datasets can be found in the `pre-trained models` directory.

**Comment by xiaohuahuaw** [comment]
Thank you for your response and the pre-trained models！
